# .github/workflows/test-ci.yml
name: Test CI/CD

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Wait for 60 seconds
        run: sleep 60

      - name: Success message
        run: echo "✅ CI/CD passed after 60 seconds!"
